In [1]:
import numpy as np

In [3]:
np.random.randn(10)

array([ 1.93059949, -0.9055134 ,  1.8826308 ,  0.59317555,  0.64517529,
        0.7449012 , -0.69289027,  2.21107658, -1.53631725, -1.06749829])

In [6]:
np.random.randint(10)

7

In [7]:
np.random.randint(10, size=(2,3))

array([[0, 9, 7],
       [5, 1, 4]])

In [8]:
np.random.randint(10, size=20)

array([0, 4, 1, 8, 2, 0, 1, 4, 6, 8, 7, 6, 4, 8, 8, 8, 2, 1, 6, 6])

In [9]:
np.random.randint(10, size=20).reshape(4,5)

array([[5, 0, 3, 2, 7],
       [1, 7, 6, 0, 6],
       [5, 1, 1, 8, 9],
       [9, 6, 3, 8, 5]])

# 陣列的運算

In [10]:
a = np.random.randint(10, size=20).reshape(4,5)

In [11]:
b = np.random.randint(10, size=20).reshape(4,5)

In [12]:
a

array([[7, 6, 3, 7, 9],
       [1, 9, 6, 8, 5],
       [1, 8, 8, 0, 0],
       [5, 7, 1, 9, 7]])

In [13]:
b

array([[1, 8, 6, 3, 9],
       [7, 1, 7, 2, 9],
       [8, 3, 7, 5, 0],
       [3, 9, 9, 7, 1]])

In [14]:
a + b

array([[ 8, 14,  9, 10, 18],
       [ 8, 10, 13, 10, 14],
       [ 9, 11, 15,  5,  0],
       [ 8, 16, 10, 16,  8]])

In [15]:
a - b

array([[ 6, -2, -3,  4,  0],
       [-6,  8, -1,  6, -4],
       [-7,  5,  1, -5,  0],
       [ 2, -2, -8,  2,  6]])

In [16]:
a * b

array([[ 7, 48, 18, 21, 81],
       [ 7,  9, 42, 16, 45],
       [ 8, 24, 56,  0,  0],
       [15, 63,  9, 63,  7]])

In [17]:
a / b

C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[7.        , 0.75      , 0.5       , 2.33333333, 1.        ],
       [0.14285714, 9.        , 0.85714286, 4.        , 0.55555556],
       [0.125     , 2.66666667, 1.14285714, 0.        ,        nan],
       [1.66666667, 0.77777778, 0.11111111, 1.28571429, 7.        ]])

In [18]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
np.mat(a)

matrix([[7, 6, 3, 7, 9],
        [1, 9, 6, 8, 5],
        [1, 8, 8, 0, 0],
        [5, 7, 1, 9, 7]])

# 矩陣的運算

In [20]:
A = np.mat(a)

In [21]:
B = np.mat(b)

In [22]:
A

matrix([[7, 6, 3, 7, 9],
        [1, 9, 6, 8, 5],
        [1, 8, 8, 0, 0],
        [5, 7, 1, 9, 7]])

In [23]:
B

matrix([[1, 8, 6, 3, 9],
        [7, 1, 7, 2, 9],
        [8, 3, 7, 5, 0],
        [3, 9, 9, 7, 1]])

In [24]:
A + B

matrix([[ 8, 14,  9, 10, 18],
        [ 8, 10, 13, 10, 14],
        [ 9, 11, 15,  5,  0],
        [ 8, 16, 10, 16,  8]])

In [25]:
A - B

matrix([[ 6, -2, -3,  4,  0],
        [-6,  8, -1,  6, -4],
        [-7,  5,  1, -5,  0],
        [ 2, -2, -8,  2,  6]])

In [26]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [27]:
a = np.mat(np.random.randint(10, size=20).reshape(4,5))

In [28]:
b = np.random.randint(10, size=20).reshape(5,4)

In [29]:
a * b

matrix([[ 64,  22, 110, 109],
        [136, 114, 174, 155],
        [112, 100, 134, 164],
        [ 44,  48,  60,  95]])

In [30]:
a 

matrix([[1, 6, 2, 1, 9],
        [7, 6, 6, 7, 5],
        [2, 6, 8, 8, 3],
        [0, 2, 6, 3, 2]])

In [31]:
b

array([[6, 6, 8, 0],
       [5, 0, 6, 2],
       [2, 5, 4, 9],
       [6, 6, 4, 7],
       [2, 0, 6, 8]])

# Array 常用函數

In [32]:
a = np.random.randint(10, size=20).reshape(4,5)

In [33]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a

array([[4, 7, 5, 2, 1],
       [0, 0, 0, 6, 1],
       [5, 0, 0, 3, 7],
       [9, 1, 6, 8, 6]])

In [35]:
sum(a)

array([18,  8, 11, 19, 15])

In [36]:
sum(a[0])

19

In [45]:
sum(a[:1])

array([4, 7, 5, 2, 1])

# Slicing 操作

In [46]:
arr = np.arange(12).reshape(3,4)

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
slice1 = arr[1:2,1:2]

In [49]:
slice1

array([[5]])

In [50]:
slice2 = arr[0:2, 0:2]

In [51]:
slice2

array([[0, 1],
       [4, 5]])

In [52]:
slice3 = arr[:,0:3]

In [53]:
slice3

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [54]:
slice3 = arr[:,::2]

In [55]:
slice3

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# 使用pickle序列化numpy array

In [66]:
import pickle
import numpy as np

In [57]:
x = np.arange(10)

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
f = open('x.pkl', 'wb')

In [70]:
pickle.dump(x, f)

In [71]:
!ls

'ls' 不是內部或外部命令、可執行的程式或批次檔。


In [72]:
f = open('x.pkl', 'rb')

In [73]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.save('one_array', x)

In [76]:
!ls

'ls' 不是內部或外部命令、可執行的程式或批次檔。


In [77]:
!dir

 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  C419-74C2

 C:\Users\Allen\PythonLab 的目錄

2018/10/30  下午 02:39    <DIR>          .
2018/10/30  下午 02:39    <DIR>          ..
2018/10/30  下午 02:05    <DIR>          .ipynb_checkpoints
2018/10/30  下午 02:38               168 .npy
2018/10/30  下午 02:37            20,544 ArrayLab01.ipynb
2018/10/30  下午 02:39               168 one_array.npy
2018/10/29  下午 11:15             8,713 Python3.ipynb
2018/10/29  下午 10:27             1,309 PythonLab01.ipynb
2018/10/30  下午 02:38               390 x.pk1
2018/10/30  下午 02:38               195 x.pkl
               7 個檔案          31,487 位元組
               3 個目錄  107,937,013,760 位元組可用


In [78]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
y = np.arrange(20)

AttributeError: module 'numpy' has no attribute 'arrange'

In [80]:
y = np.arange(20)

In [81]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
np.savez('tow_array.npz', a=x, b=y)

In [89]:
c = np.load('two_array.npz')

FileNotFoundError: [Errno 2] No such file or directory: 'two_array.npy'

In [90]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
np.savez('tow_array.npz', a=x, b=y)

In [94]:
!dir

 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  C419-74C2

 C:\Users\Allen\PythonLab 的目錄

2018/10/30  下午 02:45    <DIR>          .
2018/10/30  下午 02:45    <DIR>          ..
2018/10/30  下午 02:05    <DIR>          .ipynb_checkpoints
2018/10/30  下午 02:38               168 .npy
2018/10/30  下午 02:45            25,623 ArrayLab01.ipynb
2018/10/30  下午 02:39               168 one_array.npy
2018/10/29  下午 11:15             8,713 Python3.ipynb
2018/10/29  下午 10:27             1,309 PythonLab01.ipynb
2018/10/30  下午 02:45               570 tow_array.npy.npz
2018/10/30  下午 02:46               570 tow_array.npz
2018/10/30  下午 02:38               390 x.pk1
2018/10/30  下午 02:38               195 x.pkl
               9 個檔案          37,706 位元組
               3 個目錄  107,939,532,800 位元組可用


In [96]:
c = np.load('two_array.npz')

FileNotFoundError: [Errno 2] No such file or directory: 'two_array.npz'

In [97]:
np.savez('tow_array', a=x, b=y)

In [99]:
c = np.load('two_array')

FileNotFoundError: [Errno 2] No such file or directory: 'two_array'

In [100]:
!dir

 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  C419-74C2

 C:\Users\Allen\PythonLab 的目錄

2018/10/30  下午 02:45    <DIR>          .
2018/10/30  下午 02:45    <DIR>          ..
2018/10/30  下午 02:05    <DIR>          .ipynb_checkpoints
2018/10/30  下午 02:38               168 .npy
2018/10/30  下午 02:45            25,623 ArrayLab01.ipynb
2018/10/30  下午 02:39               168 one_array.npy
2018/10/29  下午 11:15             8,713 Python3.ipynb
2018/10/29  下午 10:27             1,309 PythonLab01.ipynb
2018/10/30  下午 02:45               570 tow_array.npy.npz
2018/10/30  下午 02:47               570 tow_array.npz
2018/10/30  下午 02:38               390 x.pk1
2018/10/30  下午 02:38               195 x.pkl
               9 個檔案          37,706 位元組
               3 個目錄  107,939,172,352 位元組可用


In [102]:
c = np.load('two_array.npz')

FileNotFoundError: [Errno 2] No such file or directory: 'two_array.npz'

In [103]:
c = np.load('two_array')

FileNotFoundError: [Errno 2] No such file or directory: 'two_array'

In [3]:
import numpy as np
list1 = [1, 2, 3, 4]
list2 = [4, 5, 6, 7]

In [4]:
array2 = np.array([list1,list2])

In [5]:
array2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

# 陣列的屬性

In [8]:
array2.shape
array2.size
array2.dtype

dtype('int32')