# 利用 arange 創建 array

In [1]:
import numpy as np

In [2]:
# 創建數值為 1~9的陣列
array1 = np.arange(1, 10)

In [3]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 創建數值為 1~9且間隔為2的陣列
array1 = np.arange(1,10,2)

In [5]:
array1

array([1, 3, 5, 7, 9])

In [9]:
# 創建一維全0陣列
array1 = np.zeros(5)

In [8]:
array1

array([0., 0., 0., 0., 0.])

In [10]:
# 創建二維全0陣列
array1 = np.zeros([2,3])

In [11]:
array1

array([[0., 0., 0.],
       [0., 0., 0.]])

# 訪問一維陣列的元素

In [16]:
a = np.arange(1, 10)

In [17]:
a[1]

2

In [15]:
# 訪問索引1~4的陣列
a[1:5]

array([2, 3, 4, 5])

In [18]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b[1][0]

4

In [21]:
b[1,0]

4

In [22]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c[:2,1:]

array([[2, 3],
       [5, 6]])

In [25]:
c[1,0]

4